name: pickled_cucumber
description: A cucumber implementation for Dart.
version: 1.0.1
repository: https://github.com/PiotrFLEURY/pickled_cucumber

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  code_builder: ^4.9.0
  dart_style: ^2.3.4
  file: ^6.1.4
  test: ^1.24.0
  source_gen: ^1.4.0

dev_dependencies:
  lints: ^3.0.0
